name: npm cli check
on:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - run: npx --yes genaiscript --help
